/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_first (void)
{
  GtkWidget *first;
  GtkWidget *fixed1;
  GtkWidget *label_role;
  GtkWidget *label_pre;
  GtkWidget *label_nom;
  GtkWidget *entry_recherche;
  GtkWidget *label_recherche;
  GtkWidget *treeview1;
  GtkWidget *button_sup;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label6;
  GtkWidget *affiche;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label21;
  GtkWidget *recherche;
  GtkWidget *image14;
  GtkWidget *best;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label29;
  GtkWidget *button_ajout;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image17;
  GtkWidget *label31;
  GtkWidget *button_modif;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image18;
  GtkWidget *label32;
  GtkWidget *image13;
  GtkWidget *image1;
  GtkWidget *type;
  GtkWidget *ingred;
  GtkWidget *qut;
  GtkWidget *etat;

  first = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (first), _("first"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (first), fixed1);

  label_role = gtk_label_new (_("Role : Nutritionniste"));
  gtk_widget_show (label_role);
  gtk_fixed_put (GTK_FIXED (fixed1), label_role, 24, 408);
  gtk_widget_set_size_request (label_role, 144, 24);

  label_pre = gtk_label_new (_("Pr\303\251nom : Gannouni"));
  gtk_widget_show (label_pre);
  gtk_fixed_put (GTK_FIXED (fixed1), label_pre, 0, 384);
  gtk_widget_set_size_request (label_pre, 176, 17);

  label_nom = gtk_label_new (_("Nom : Med Amine"));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_nom, 16, 352);
  gtk_widget_set_size_request (label_nom, 144, 32);

  entry_recherche = gtk_entry_new ();
  gtk_widget_show (entry_recherche);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_recherche, 520, 48);
  gtk_widget_set_size_request (entry_recherche, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche), 8226);

  label_recherche = gtk_label_new (_("Recherche :"));
  gtk_widget_show (label_recherche);
  gtk_fixed_put (GTK_FIXED (fixed1), label_recherche, 416, 48);
  gtk_widget_set_size_request (label_recherche, 104, 32);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 184, 136);
  gtk_widget_set_size_request (treeview1, 440, 232);

  button_sup = gtk_button_new ();
  gtk_widget_show (button_sup);
  gtk_fixed_put (GTK_FIXED (fixed1), button_sup, 432, 376);
  gtk_widget_set_size_request (button_sup, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_sup), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("suprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  affiche = gtk_button_new ();
  gtk_widget_show (affiche);
  gtk_fixed_put (GTK_FIXED (fixed1), affiche, 536, 376);
  gtk_widget_set_size_request (affiche, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (affiche), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("affichage"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox8), label21, FALSE, FALSE, 0);

  recherche = gtk_button_new ();
  gtk_widget_show (recherche);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche, 688, 48);
  gtk_widget_set_size_request (recherche, 66, 29);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (recherche), image14);

  best = gtk_button_new ();
  gtk_widget_show (best);
  gtk_fixed_put (GTK_FIXED (fixed1), best, 624, 216);
  gtk_widget_set_size_request (best, 128, 64);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (best), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("meilleur menu"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox12), label29, FALSE, FALSE, 0);

  button_ajout = gtk_button_new ();
  gtk_widget_show (button_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajout, 320, 376);
  gtk_widget_set_size_request (button_ajout, 96, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_ajout), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox14), image17, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox14), label31, FALSE, FALSE, 0);

  button_modif = gtk_button_new ();
  gtk_widget_show (button_modif);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modif, 208, 376);
  gtk_widget_set_size_request (button_modif, 104, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_modif), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image18 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox15), image18, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox15), label32, FALSE, FALSE, 0);

  image13 = create_pixmap (first, "Logo_ESPRIT_Ariana.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1), image13, 24, 64);
  gtk_widget_set_size_request (image13, 208, 80);

  image1 = create_pixmap (first, "257574917_412638340404115_2210628859668054255_n.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 8, 128);
  gtk_widget_set_size_request (image1, 176, 208);

  type = gtk_label_new ("");
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed1), type, 424, 96);
  gtk_widget_set_size_request (type, 49, 17);

  ingred = gtk_label_new ("");
  gtk_widget_show (ingred);
  gtk_fixed_put (GTK_FIXED (fixed1), ingred, 512, 96);
  gtk_widget_set_size_request (ingred, 49, 17);

  qut = gtk_label_new ("");
  gtk_widget_show (qut);
  gtk_fixed_put (GTK_FIXED (fixed1), qut, 664, 96);
  gtk_widget_set_size_request (qut, 49, 17);

  etat = gtk_label_new ("");
  gtk_widget_show (etat);
  gtk_fixed_put (GTK_FIXED (fixed1), etat, 584, 96);
  gtk_widget_set_size_request (etat, 49, 17);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_sup, "clicked",
                    G_CALLBACK (on_button_sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) affiche, "clicked",
                    G_CALLBACK (on_affiche_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche, "clicked",
                    G_CALLBACK (on_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) best, "clicked",
                    G_CALLBACK (on_best_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajout, "clicked",
                    G_CALLBACK (on_button_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modif, "clicked",
                    G_CALLBACK (on_button_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (first, first, "first");
  GLADE_HOOKUP_OBJECT (first, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (first, label_role, "label_role");
  GLADE_HOOKUP_OBJECT (first, label_pre, "label_pre");
  GLADE_HOOKUP_OBJECT (first, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (first, entry_recherche, "entry_recherche");
  GLADE_HOOKUP_OBJECT (first, label_recherche, "label_recherche");
  GLADE_HOOKUP_OBJECT (first, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (first, button_sup, "button_sup");
  GLADE_HOOKUP_OBJECT (first, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (first, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (first, image4, "image4");
  GLADE_HOOKUP_OBJECT (first, label6, "label6");
  GLADE_HOOKUP_OBJECT (first, affiche, "affiche");
  GLADE_HOOKUP_OBJECT (first, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (first, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (first, image9, "image9");
  GLADE_HOOKUP_OBJECT (first, label21, "label21");
  GLADE_HOOKUP_OBJECT (first, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (first, image14, "image14");
  GLADE_HOOKUP_OBJECT (first, best, "best");
  GLADE_HOOKUP_OBJECT (first, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (first, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (first, image15, "image15");
  GLADE_HOOKUP_OBJECT (first, label29, "label29");
  GLADE_HOOKUP_OBJECT (first, button_ajout, "button_ajout");
  GLADE_HOOKUP_OBJECT (first, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (first, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (first, image17, "image17");
  GLADE_HOOKUP_OBJECT (first, label31, "label31");
  GLADE_HOOKUP_OBJECT (first, button_modif, "button_modif");
  GLADE_HOOKUP_OBJECT (first, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (first, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (first, image18, "image18");
  GLADE_HOOKUP_OBJECT (first, label32, "label32");
  GLADE_HOOKUP_OBJECT (first, image13, "image13");
  GLADE_HOOKUP_OBJECT (first, image1, "image1");
  GLADE_HOOKUP_OBJECT (first, type, "type");
  GLADE_HOOKUP_OBJECT (first, ingred, "ingred");
  GLADE_HOOKUP_OBJECT (first, qut, "qut");
  GLADE_HOOKUP_OBJECT (first, etat, "etat");

  return first;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed2;
  GtkWidget *type;
  GtkWidget *label22;
  GtkWidget *input1;
  GtkWidget *input2;
  GtkWidget *input3;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *input4;
  GtkWidget *label25;
  GtkWidget *input5;
  GtkWidget *ret_ajout;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label27;
  GtkWidget *button_appajout;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label18;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajout"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout), fixed2);

  type = gtk_label_new (_("Type de repas :"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed2), type, 0, 88);
  gtk_widget_set_size_request (type, 136, 32);

  label22 = gtk_label_new (_("id:"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 32, 64);
  gtk_widget_set_size_request (label22, 49, 17);

  input1 = gtk_entry_new ();
  gtk_widget_show (input1);
  gtk_fixed_put (GTK_FIXED (fixed2), input1, 120, 64);
  gtk_widget_set_size_request (input1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input1), 8226);

  input2 = gtk_entry_new ();
  gtk_widget_show (input2);
  gtk_fixed_put (GTK_FIXED (fixed2), input2, 128, 96);
  gtk_widget_set_size_request (input2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input2), 8226);

  input3 = gtk_entry_new ();
  gtk_widget_show (input3);
  gtk_fixed_put (GTK_FIXED (fixed2), input3, 128, 128);
  gtk_widget_set_size_request (input3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input3), 8226);

  label24 = gtk_label_new (_("ingredient :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 16, 128);
  gtk_widget_set_size_request (label24, 104, 24);

  label23 = gtk_label_new (_("etat :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 16, 160);
  gtk_widget_set_size_request (label23, 88, 24);

  input4 = gtk_entry_new ();
  gtk_widget_show (input4);
  gtk_fixed_put (GTK_FIXED (fixed2), input4, 120, 160);
  gtk_widget_set_size_request (input4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input4), 8226);

  label25 = gtk_label_new (_("quantit\303\251e :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 16, 192);
  gtk_widget_set_size_request (label25, 112, 24);

  input5 = gtk_entry_new ();
  gtk_widget_show (input5);
  gtk_fixed_put (GTK_FIXED (fixed2), input5, 120, 192);
  gtk_widget_set_size_request (input5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (input5), 8226);

  ret_ajout = gtk_button_new ();
  gtk_widget_show (ret_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), ret_ajout, 352, 264);
  gtk_widget_set_size_request (ret_ajout, 128, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ret_ajout), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox10), label27, FALSE, FALSE, 0);

  button_appajout = gtk_button_new ();
  gtk_widget_show (button_appajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button_appajout, 208, 264);
  gtk_widget_set_size_request (button_appajout, 122, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_appajout), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ret_ajout, "clicked",
                    G_CALLBACK (on_ret_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_appajout, "clicked",
                    G_CALLBACK (on_button_appajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout, type, "type");
  GLADE_HOOKUP_OBJECT (ajout, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajout, input1, "input1");
  GLADE_HOOKUP_OBJECT (ajout, input2, "input2");
  GLADE_HOOKUP_OBJECT (ajout, input3, "input3");
  GLADE_HOOKUP_OBJECT (ajout, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajout, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajout, input4, "input4");
  GLADE_HOOKUP_OBJECT (ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (ajout, input5, "input5");
  GLADE_HOOKUP_OBJECT (ajout, ret_ajout, "ret_ajout");
  GLADE_HOOKUP_OBJECT (ajout, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajout, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajout, image11, "image11");
  GLADE_HOOKUP_OBJECT (ajout, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajout, button_appajout, "button_appajout");
  GLADE_HOOKUP_OBJECT (ajout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajout, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajout, label18, "label18");

  return ajout;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label_qut;
  GtkWidget *id_mod;
  GtkWidget *entry_idmod;
  GtkWidget *type_mod;
  GtkWidget *etat_mod;
  GtkWidget *ingredient_mod;
  GtkWidget *ret_mod;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *button_app;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *comboboxentry1;
  GtkWidget *checkbutton9;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton8;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modif"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier), fixed3);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 512, 24);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label_qut = gtk_label_new (_("Quantit\303\251 :"));
  gtk_widget_show (label_qut);
  gtk_fixed_put (GTK_FIXED (fixed3), label_qut, 424, 24);
  gtk_widget_set_size_request (label_qut, 88, 32);

  id_mod = gtk_label_new (_("id de repas :"));
  gtk_widget_show (id_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), id_mod, 8, 64);
  gtk_widget_set_size_request (id_mod, 176, 25);

  entry_idmod = gtk_entry_new ();
  gtk_widget_show (entry_idmod);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_idmod, 144, 64);
  gtk_widget_set_size_request (entry_idmod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idmod), 8226);

  type_mod = gtk_label_new (_("le type de repas :"));
  gtk_widget_show (type_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), type_mod, 40, 112);
  gtk_widget_set_size_request (type_mod, 152, 25);

  etat_mod = gtk_label_new (_("l'etat de repas :"));
  gtk_widget_show (etat_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), etat_mod, 16, 208);
  gtk_widget_set_size_request (etat_mod, 152, 24);

  ingredient_mod = gtk_label_new (_("les ingredients de repas :"));
  gtk_widget_show (ingredient_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), ingredient_mod, 24, 288);
  gtk_widget_set_size_request (ingredient_mod, 184, 32);

  ret_mod = gtk_button_new ();
  gtk_widget_show (ret_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), ret_mod, 416, 424);
  gtk_widget_set_size_request (ret_mod, 112, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (ret_mod), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox11), label28, FALSE, FALSE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Petit dejeuner"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 32, 160);
  gtk_widget_set_size_request (radiobutton1, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Dejeuner"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 200, 160);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 344, 160);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  button_app = gtk_button_new ();
  gtk_widget_show (button_app);
  gtk_fixed_put (GTK_FIXED (fixed3), button_app, 264, 424);
  gtk_widget_set_size_request (button_app, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_app), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("fruit"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton6, 408, 344);
  gtk_widget_set_size_request (checkbutton6, 126, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("lait"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 24, 328);
  gtk_widget_set_size_request (checkbutton1, 136, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("jus"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 24, 352);
  gtk_widget_set_size_request (checkbutton2, 126, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("viande"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton3, 240, 320);
  gtk_widget_set_size_request (checkbutton3, 126, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("poisson"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton4, 240, 352);
  gtk_widget_set_size_request (checkbutton4, 126, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("c\303\251r\303\251ale"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton5, 408, 320);
  gtk_widget_set_size_request (checkbutton5, 126, 24);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 176, 208);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Entr\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Plat_principale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Dessert"));

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("salade"));
  gtk_widget_show (checkbutton9);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton9, 408, 368);
  gtk_widget_set_size_request (checkbutton9, 118, 24);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("poulet"));
  gtk_widget_show (checkbutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton7, 24, 384);
  gtk_widget_set_size_request (checkbutton7, 118, 24);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("pate"));
  gtk_widget_show (checkbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton8, 240, 376);
  gtk_widget_set_size_request (checkbutton8, 118, 24);

  g_signal_connect ((gpointer) ret_mod, "clicked",
                    G_CALLBACK (on_ret_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_app, "clicked",
                    G_CALLBACK (on_button_app_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6, "toggled",
                    G_CALLBACK (on_checkbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton9, "toggled",
                    G_CALLBACK (on_checkbutton9_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton7, "toggled",
                    G_CALLBACK (on_checkbutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton8, "toggled",
                    G_CALLBACK (on_checkbutton8_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (modifier, label_qut, "label_qut");
  GLADE_HOOKUP_OBJECT (modifier, id_mod, "id_mod");
  GLADE_HOOKUP_OBJECT (modifier, entry_idmod, "entry_idmod");
  GLADE_HOOKUP_OBJECT (modifier, type_mod, "type_mod");
  GLADE_HOOKUP_OBJECT (modifier, etat_mod, "etat_mod");
  GLADE_HOOKUP_OBJECT (modifier, ingredient_mod, "ingredient_mod");
  GLADE_HOOKUP_OBJECT (modifier, ret_mod, "ret_mod");
  GLADE_HOOKUP_OBJECT (modifier, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modifier, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (modifier, button_app, "button_app");
  GLADE_HOOKUP_OBJECT (modifier, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modifier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifier, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (modifier, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (modifier, checkbutton8, "checkbutton8");

  return modifier;
}

GtkWidget*
create_sup (void)
{
  GtkWidget *sup;
  GtkWidget *fixed4;
  GtkWidget *entry3;
  GtkWidget *label_entree;
  GtkWidget *button_supp;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label17;
  GtkWidget *ret_sup;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label26;

  sup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (sup), _("suprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (sup), fixed4);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 208, 40);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label_entree = gtk_label_new (_("entrer l'element \303\240 suprimer :"));
  gtk_widget_show (label_entree);
  gtk_fixed_put (GTK_FIXED (fixed4), label_entree, 0, 40);
  gtk_widget_set_size_request (label_entree, 208, 24);

  button_supp = gtk_button_new ();
  gtk_widget_show (button_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supp, 80, 104);
  gtk_widget_set_size_request (button_supp, 136, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_supp), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Suprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox5), label17, FALSE, FALSE, 0);

  ret_sup = gtk_button_new ();
  gtk_widget_show (ret_sup);
  gtk_fixed_put (GTK_FIXED (fixed4), ret_sup, 256, 104);
  gtk_widget_set_size_request (ret_sup, 144, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ret_sup), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supp, "clicked",
                    G_CALLBACK (on_button_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) ret_sup, "clicked",
                    G_CALLBACK (on_ret_sup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sup, sup, "sup");
  GLADE_HOOKUP_OBJECT (sup, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (sup, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (sup, label_entree, "label_entree");
  GLADE_HOOKUP_OBJECT (sup, button_supp, "button_supp");
  GLADE_HOOKUP_OBJECT (sup, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (sup, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (sup, image6, "image6");
  GLADE_HOOKUP_OBJECT (sup, label17, "label17");
  GLADE_HOOKUP_OBJECT (sup, ret_sup, "ret_sup");
  GLADE_HOOKUP_OBJECT (sup, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (sup, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (sup, image10, "image10");
  GLADE_HOOKUP_OBJECT (sup, label26, "label26");

  return sup;
}

GtkWidget*
create_affichage (void)
{
  GtkWidget *affichage;
  GtkWidget *fixed5;
  GtkWidget *aff;
  GtkWidget *button_ret_aff;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label20;
  GtkWidget *scrolledwindow1;

  affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage), _("affichage"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (affichage), fixed5);

  aff = gtk_label_new (_("affichage de menu :"));
  gtk_widget_show (aff);
  gtk_fixed_put (GTK_FIXED (fixed5), aff, 80, 40);
  gtk_widget_set_size_request (aff, 184, 16);

  button_ret_aff = gtk_button_new ();
  gtk_widget_show (button_ret_aff);
  gtk_fixed_put (GTK_FIXED (fixed5), button_ret_aff, 168, 288);
  gtk_widget_set_size_request (button_ret_aff, 96, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ret_aff), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox7), label20, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 48, 376);
  gtk_widget_set_size_request (scrolledwindow1, 352, 224);

  g_signal_connect ((gpointer) button_ret_aff, "clicked",
                    G_CALLBACK (on_button_ret_aff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage, affichage, "affichage");
  GLADE_HOOKUP_OBJECT (affichage, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (affichage, aff, "aff");
  GLADE_HOOKUP_OBJECT (affichage, button_ret_aff, "button_ret_aff");
  GLADE_HOOKUP_OBJECT (affichage, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (affichage, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (affichage, image8, "image8");
  GLADE_HOOKUP_OBJECT (affichage, label20, "label20");
  GLADE_HOOKUP_OBJECT (affichage, scrolledwindow1, "scrolledwindow1");

  return affichage;
}

GtkWidget*
create_best (void)
{
  GtkWidget *best;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *ret_bestt;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label30;
  GtkWidget *calendar1;

  best = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (best), _("Meilleur menu"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (best), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 88, 96);
  gtk_widget_set_size_request (treeview2, 368, 248);

  ret_bestt = gtk_button_new ();
  gtk_widget_show (ret_bestt);
  gtk_fixed_put (GTK_FIXED (fixed6), ret_bestt, 152, 352);
  gtk_widget_set_size_request (ret_bestt, 120, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (ret_bestt), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox13), label30, FALSE, FALSE, 0);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar1, 496, 128);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  g_signal_connect ((gpointer) ret_bestt, "clicked",
                    G_CALLBACK (on_ret_bestt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (best, best, "best");
  GLADE_HOOKUP_OBJECT (best, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (best, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (best, ret_bestt, "ret_bestt");
  GLADE_HOOKUP_OBJECT (best, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (best, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (best, image16, "image16");
  GLADE_HOOKUP_OBJECT (best, label30, "label30");
  GLADE_HOOKUP_OBJECT (best, calendar1, "calendar1");

  return best;
}

