/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_first (void);
GtkWidget* create_ajout (void);
GtkWidget* create_modifier (void);
GtkWidget* create_sup (void);
GtkWidget* create_affichage (void);
GtkWidget* create_best (void);
